name: additive2
dependencies:
  - python=3.6
  - pip
  - pandas
  - ipykernel
  - dask
  - distributed
  - scikit-learn
  - opencv
  - imageio
  - seaborn
  - tensorflow<2

  - pip:
    - sh
    - pathos
    - joblib
    - statsmodels
    - "--editable=."
